### ISSUE TITLE
Newbie question: How do you use these new assertions?

### ISSUE THREAD

**Issue by SuneRadich** [maxgalbu/nightwatch-custom-commands-assertions#1]
This might be a stupid newbie question, as I am still quite new to Node, Nightwatch and Selenium. But how do I correctly import and use these custom assertions and commands?

**Comment by maxgalbu** [comment]
You're right, I'll put in the readme some info on how to do it.

**Comment by maxgalbu** [comment]
Done. Please let me know if the instructions work for you :santa:
