### ISSUE TITLE
Doesn't work with PageObjects in Nightwatch.js

### ISSUE THREAD

**Issue by drptbl** [maxgalbu/nightwatch-custom-commands-assertions#11]
Just a simple question - does this custom assertions support Nightwatch.js page objects? I’m not able to get it working, so I think they doesn’t or I’m doing something wrong.

When I use:
`browser.page.homePage().section.mainSearch.jqueryClick("@searchResults:contains('Barack Obama')”)`

It doesn’t work (provided log in gist).

When I’m not using page objects - it works.
`browser.jqueryClick(".search-result-name:contains('Barack Obama')”)`

When I’m using normal `.click` command from nightwatch.js, it works with same pageObjects but as you probably know it only selects first element it finds.

Can you please clarify? Thanks!

https://gist.github.com/drptbl/a3cbfcee551fb4923e77

**Comment by maxgalbu** [comment]
(same reply as the mail)

I've tested page objects with custom commands and from what I see they work fine, as long as you use only the element name (eg: @searchResults) and not the element name + other selectors (like in your example, @searchResults:contains('Barack Obama')). Did you try with .click()? You should have the same problem.

(I looked here: https://github.com/nightwatchjs/nightwatch/blob/master/lib/page-object/command-wrapper.js and it seems that the commands are wrapped with the page objects function, so when you call the custom command the selector is first passed thought the page object code)

**Comment by drptbl** [comment]
Tried to make this work those ways:
`browser.page.homePage().section.mainSearch.jqueryClick('@searchResults')` - didn't work.

Then I've created new `testElement` in PageObjects with same CSS as `searchResults` - I just removed it from section so there are no sections. Then I've tried this command:
`browser.page.homePage().jqueryClick('@testElement')` - didn't work too.

I've tried `.click()` and it works fine with sections and without sections, just it clicks on first element it finds and I want to click on a CSS containing text, so I need `:contains` feature which is missing in Nightwatch.js.

And then I moved forward and I did this:
`var testElementSelector = browser.page.homePage().section.fakeSection.selector
browser.jqueryClick(testElementSelector)`

I took selector of `fakeSection` which has the same selector as `testElement` and `searchResults` - it's just a new section I've created to test this stuff, probably I could take selector of `testElement`, but I don't know how yet, so I converted this element to new section.

And it worked! But when you change this to:
`browser.jqueryClick(testElementSelector, 'Barack Obama')`
as you probably already know it doesn't work :( 
(actually it works but it clicks on first element it finds, he doesn't take second value which is "Barack Obama" and it throws an error in console).

And here's an error:

TypeError: undefined is not a function
    at Object.<anonymous> (/Users/jm/repos/nightwatchpoc/node_modules/nightwatch-custom-commands-assertions/js/commands/jqueryClick.js:28:25)
    at HttpRequest.<anonymous> (/usr/local/lib/node_modules/nightwatch/lib/index.js:315:20)
    at HttpRequest.emit (events.js:110:17)
    at HttpRequest.<anonymous> (/usr/local/lib/node_modules/nightwatch/lib/index.js:337:15)
    at HttpRequest.emit (events.js:118:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nightwatch/lib/http/request.js:148:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
 ✔ Element <.thing-title> was visible after 49 milliseconds.
Error while running [Home Page / Home Page Spec / You should be able to search for defined string using top search input field]:
undefined is not a function

FAILED:  1 errors and 3 passed (4.3s)
Closing down everything after testing..

---

TEST FAILURE: 1 error during execution, 0 assertions failed, 6 passed (9.47s)

Thanks for all help and answer! :+1:

**Comment by maxgalbu** [comment]
Can you share a simple example?

**Comment by searchresults** [comment]
I contain Obama?
Sweet.

**Comment by drptbl** [comment]
@maxgalbu Do you want a test with pageobjects? I can share it privately if you wish. Confirmed this doesn't work with pageObjects and sections.

**Comment by maxgalbu** [comment]
Sorry for the late response, I added a [test with pageObjects](https://github.com/maxgalbu/nightwatch-custom-commands-assertions/blob/1bf1389f5e7f2e11570fdd84f80c62a6246ec63a/tests/runTests.js#L6-L15) ([here's the page object](https://github.com/maxgalbu/nightwatch-custom-commands-assertions/blob/master/tests/page_objects/test.js)). Does the test cover your case? Otherwise please share your code if you can :)

**Comment by maxgalbu** [comment]
I found what the problem was, my custom commands weren't working with the section feature of the pageobjects, I had to do some work to get it fixed :) should be ok now, please try again
