### ISSUE TITLE
Request:  mysql assertion

### ISSUE THREAD

**Issue by mtvan** [maxgalbu/nightwatch-custom-commands-assertions#16]
After doing an action, I would like to verify that in mysql it set that field to the appropriate value.  In this case a simple 0 or a 1

**Comment by maxgalbu** [comment]
You could use the .shell() command to do something like this:

``` js
browser.shell("mysql -e 'SELECT something FROM table' --xml", function(err, stdout) {
     //parse the xml from 'stdout' and read the results
});
```
