### ISSUE TITLE
WaitForJqueryAjaxRequest incorrect Example

### ISSUE THREAD

**Issue by yusufilkeroguz** [maxgalbu/nightwatch-custom-commands-assertions#23]
![image](https://user-images.githubusercontent.com/3788174/27071747-c11e7b7c-5026-11e7-83bc-3be55472b1a7.png)

for WebStorm, "WaitForJqueryAjaxRequest" is a function and "waitForJqueryAjaxRequest" is not defined. When i run nightwatch, "WaitForJqueryAjaxRequest" is not a function but "waitForJqueryAjaxRequest" is working. 

![image](https://user-images.githubusercontent.com/3788174/27071752-cc1b9334-5026-11e7-8ab0-0fc327953713.png)

in jsDoc, example is wrong.

Note: Excuse My English :)

**Comment by maxgalbu** [comment]
The exported object is a class so the first letter is capital. It's the same for nightwatch commands too:

https://github.com/nightwatchjs/nightwatch/blob/master/lib/api/element-commands/waitForElementVisible.js
