### ISSUE TITLE
feature request: waitForJqueryElementVisible

### ISSUE THREAD

**Issue by zeroasterisk** [maxgalbu/nightwatch-custom-commands-assertions#5]
I'd love to see an implementation of `waitForElementVisible` refactored to work with `jqueryElementPresent`

perhaps: `browser.waitForJqueryElementVisible(selector, time, abortOnFail, callback, msg)`

I tried my hand on implementing, but was not able to get it working...

ref:
- https://github.com/beatfactor/nightwatch/blob/master/lib/api/commands/_waitForElement.js
- https://github.com/beatfactor/nightwatch/blob/master/lib/api/commands/waitForElementPresent.js
- https://github.com/beatfactor/nightwatch/blob/master/lib/api/commands/waitForElementVisible.js

**Comment by maxgalbu** [comment]
I'll try to add it on this weekend :+1:

**Comment by maxgalbu** [comment]
I've added a waitForJqueryElement, should be enough for every jquery need:

```
browser.waitForJqueryElement(".yourclass:visible");
```

**Comment by zeroasterisk** [comment]
SWEET!  thanks! :+1:
